### ISSUE TITLE
 ERROR: no function clause matching in GenServer.whereis/1

### ISSUE THREAD

**Issue by danish-nadeem** [quantum-elixir/quantum-core#360] opened 2018-08-13 11:11 UTC
Followed the exact instructions as they were given, the configuration seems to be working but the application returns an error whenever the task runs.

### Environment
elixir: Erlang/OTP 21 and Elixir 1.6.6 (compiled with OTP 19)
quantum: 2.3.0

debug/info when application is launched:

```
[info] Running MyappWeb.Endpoint with Cowboy using http://0.0.0.0:4004
[info] [swarm on nonode@nohost] [tracker:cluster_wait] joining cluster..
[info] [swarm on nonode@nohost] [tracker:cluster_wait] no connected nodes, proceeding without sync
[debug] [swarm on nonode@nohost] [tracker:handle_call] registering #PID<0.669.0> as :"Elixir.Myapp.Libraries.Scheduler.ClusterTaskSupervisorRegistry.Group.#Reference<0.590121076.4105961474.145928>", with metadata %{}
[debug] [swarm on nonode@nohost] [tracker:handle_call] add_meta {Myapp.Libraries.Scheduler.ClusterTaskSupervisorRegistry.Group, true} to #PID<0.669.0>
[debug] [:nonode@nohost][Elixir.Quantum.JobBroadcaster] Loading Initial Jobs from Config
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Unknown last execution time, using now
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Adding job :phoenix_job
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Continuing Execution Broadcasting at -576460701918 (2018-08-13T10:14:00)
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Scheduling job for execution :phoenix_job
[debug] [:nonode@nohost][Elixir.Quantum.ExecutionBroadcaster] Continuing Execution Broadcasting at -576460641918 (2018-08-13T10:15:00)
[debug] [:nonode@nohost][Elixir.Quantum.Executor] Task for job :phoenix_job started on node [:nonode@nohost]
```

The error shortly after the above responses:

```
 started from Myapp.Scheduler.ExecutorSupervisor terminating
** (FunctionClauseError) no function clause matching in GenServer.whereis/1
    (elixir) lib/gen_server.ex:1007: GenServer.whereis({Myapp.Scheduler.Task.Supervisor, [:nonode@nohost]})
    (elixir) lib/gen_server.ex:824: GenServer.call/3
    (elixir) lib/task/supervisor.ex:363: Task.Supervisor.async/6
    (quantum) lib/quantum/executor.ex:139: Quantum.Executor.run/4
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
    (quantum) lib/quantum/executor.ex:73: Quantum.Executor.execute/5
    (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<9.113246364/0 in Quantum.Executor.start_link/2>
    Args: []

```

Can you suggest a solution?

**Comment by maennchen** [comment] 2018-08-13 11:38
Duplicate of #356, will be released with #359

**Closed by maennchen** 2018-08-13 11:38 UTC
