### ISSUE TITLE
Unexpected Error when node down

### ISSUE THREAD

**Issue by pggalaviz** [quantum-elixir/quantum-core#382] opened 2018-11-17 01:34 UTC
I'm starting to use Quantum on my app, I already use Swarm for other functionality, while experimenting (killing a node from the cluster) I get an error on the remaining running nodes, which sometimes bring down the whole app.

Here's my config: 
```
# Quantum global scheduler
config :core, Core.GlobalScheduler,
  global: true,
  jobs: [
    clear_user_sessions: [
      schedule: "@hourly",
      task: {Core.Accounts.UserSession, :clear_expired, []}
    ]
  ]
```
It just runs a function hourly to clear expired User sessions.

If I run lets say nodes A, B and C and kill B with double `ctrl+c`, I get an error in A:
```
[error] GenServer Core.GlobalScheduler.ExecutorSupervisor terminating
** (stop) no connection
Last message: {:DOWN, #Reference<0.95995212.1283457025.121179>, :process, #PID<14428.428.0>, :noconnection}
State: %ConsumerSupervisor{args: %Quantum.ExecutorSupervisor.InitOpts{cluster_task_supervisor_registry_reference: Core.GlobalScheduler.ClusterTaskSupervisorRegistry, debug_logging: true, execution_broadcaster_reference: {:via, :swarm, Core.GlobalScheduler.ExecutionBroadcaster}, task_registry_reference: {:via, :swarm, Core.GlobalScheduler.TaskRegistry}, task_supervisor_reference: Core.GlobalScheduler.Task.Supervisor}, children: %{}, max_restarts: 3, max_seconds: 5, mod: Quantum.ExecutorSupervisor, name: Core.GlobalScheduler.ExecutorSupervisor, producers: %{}, restarting: 0, restarts: [], strategy: :one_for_one, template: {Quantum.Executor, {Quantum.Executor, :start_link, [%Quantum.Executor.StartOpts{cluster_task_supervisor_registry_reference: Core.GlobalScheduler.ClusterTaskSupervisorRegistry, debug_logging: true, task_registry_reference: {:via, :swarm, Core.GlobalScheduler.TaskRegistry}, task_supervisor_reference: Core.GlobalScheduler.Task.Supervisor}]}, :temporary, 5000, :worker, [Quantum.Executor]}}
```

And from node C, I get this one:
```
[error] GenServer Core.GlobalScheduler.ExecutorSupervisor terminating
** (stop) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
Last message: {:DOWN, #Reference<0.2331623498.478150658.15799>, :process, #PID<0.428.0>, :noproc}
State: %ConsumerSupervisor{args: %Quantum.ExecutorSupervisor.InitOpts{cluster_task_supervisor_registry_reference: Core.GlobalScheduler.ClusterTaskSupervisorRegistry, debug_logging: true, execution_broadcaster_reference: {:via, :swarm, Core.GlobalScheduler.ExecutionBroadcaster}, task_registry_reference: {:via, :swarm, Core.GlobalScheduler.TaskRegistry}, task_supervisor_reference: Core.GlobalScheduler.Task.Supervisor}, children: %{}, max_restarts: 3, max_seconds: 5, mod: Quantum.ExecutorSupervisor, name: Core.GlobalScheduler.ExecutorSupervisor, producers: %{}, restarting: 0, restarts: [], strategy: :one_for_one, template: {Quantum.Executor, {Quantum.Executor, :start_link, [%Quantum.Executor.StartOpts{cluster_task_supervisor_registry_reference: Core.GlobalScheduler.ClusterTaskSupervisorRegistry, debug_logging: true, task_registry_reference: {:via, :swarm, Core.GlobalScheduler.TaskRegistry}, task_supervisor_reference: Core.GlobalScheduler.Task.Supervisor}]}, :temporary, 5000, :worker, [Quantum.Executor]}}

[info] GenStage consumer Core.GlobalScheduler.ExecutorSupervisor is stopping after receiving cancel from producer #PID<0.428.0> with reason: :noproc
```
This printed 4 times before bringing down my `Core` app, I can see there's a `max_restarts: 3` option enabled.

I don't see this errors when gracefully terminating the nodes (eg. SIGTERM signal), but what if a net split happens? Or the server just go down for malfunction?

Is there a way to prevent the running nodes to collapse when another node in the cluster simply vanishes?

**Comment by maennchen** [comment] 2018-11-17 09:02
This is a duplicate of #380 and #374 and there is currently no way to prevent that. I did not yet find a solution for this behavior.

**Closed by maennchen** 2018-11-17 09:02 UTC
Labels: bug, duplicate

**Comment by seamon** [comment] 2019-01-25 09:14
same issue from within version 2.3, have to keep using v2.2 ...

hope it's fixed soon
