### ISSUE TITLE
Cronjob delete issues

### ISSUE THREAD

**Issue by TestFirebaseLogin** [quantum-elixir/quantum-core#420] opened 2019-11-29 12:02 UTC
Cronjob delete still have cronjob running(although not visible),as when i add a job with same name again,after delete,first time the method setup for execution in cronjob code,is called as many number of times,as time elapsed after cronjob was deleted divided by time duration bet ween cronjobs.Ex- if job interval is 20 seconds and i adda job with same name after deleting it,after 40 seconds it will excute first time for 2 times.If i add job after more than 120 s it will execute first time for 6 times.

**Comment by maennchen** [comment] 2020-02-26 20:24
@TestFirebaseLogin Does this still happen on `master`?

**Comment by maennchen** [comment] 2020-02-26 20:25
Duplicate of #416

**Closed by maennchen** 2020-02-26 20:25 UTC
Labels: bug
